/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerGUI.java
 *
 * Created on Jun 17, 2011, 5:17:58 AM
 */
package server;

import dbb.KomunikacijaSaBazom;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import kab.op.domen.DomenskiObjekat;
import kab.op.domen.Osoba;
import kab.op.domen.Paket;
import kontrolerPL.KontrolerPL;
import niti.NitCekajKlijente;

/**
 *
 * @author Sale
 */
public class ServerGUI extends javax.swing.JFrame {

    /** Creates new form ServerGUI */
    public ServerGUI() {
        initComponents();
       Paket paket = new Paket();
       paket.setBrzina(1);
       paket.setCena(3);
       paket.setNazivpaketa("proba");
       paket.setPaketID("1");
      paket.setOpispaketa("opis tamo neki");
      kontrolerPL.KontrolerPL.dodajDomenskiObjekat(paket);
      kontrolerPL.KontrolerPL.dodajDomenskiObjekat(paket);
      kontrolerPL.KontrolerPL.obrisiDomenskiObjekat(paket);
      kontrolerPL.KontrolerPL.dodajDomenskiObjekat(paket);
      paket.setNazivpaketa("proba5");
      kontrolerPL.KontrolerPL.izmeniDomenskiObjekat(paket);
      
        //NitCekajKlijente nck = new NitCekajKlijente();
       // nck.start();
        //  ispisiSveOsobe();

    }

    public void ispisiSveOsobe() {
        try {

            List<DomenskiObjekat> listaOsoba = new ArrayList<DomenskiObjekat>();


            DomenskiObjekat osobaDomObjekat = new Osoba();
            System.out.println("ispisiSveOsobe1");
            listaOsoba = KomunikacijaSaBazom.vratiInstancuKomunikacijeSaBazom().vratiListuDomenskihObjekata(osobaDomObjekat);
            System.out.println("ispisiSveOsobe 2");
            for (DomenskiObjekat domenskiObjekat : listaOsoba) {
                Osoba o = (Osoba) domenskiObjekat;
                System.out.println(o.getIme());


            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
